
version: '2'

services:
  pg-master:
    build: '.'
    image: 'postgres-replication'
    restart: 'always'
    cap_add:
      - NET_ADMIN
    ports:
      - "5432:5432"
    volumes:
     - '/var/lib/postgresql/data'
     - ./docker/configs/master.env:/app.env
    expose:
     - '5432'

  pg-slave:
    build: '.'
    image: 'postgres-replication'
    restart: 'always'
    cap_add:
      - NET_ADMIN
    volumes:
     - '/var/lib/postgresql/data'
     - ./docker/configs/slave.env:/app.env
    ports:
      - "5433:5432"
    expose:
     - '5432'
    links:
     - 'pg-master'
  pg-arbiter:
    build: '.'
    image: 'postgres-replication'
    restart: 'always'
    cap_add:
      - NET_ADMIN
    volumes:
     - ./docker/configs/arbiter.env:/app.env
     - '/var/lib/postgresql/data'
    expose:
     - '5432'